[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-C", "link-arg=-Tkernel/src/kernel.ld"]

[target.riscv64gc-unknown-none-elf]
# executable automatically appended after the runner
runner = "./runner.sh"
